server {
    listen 80;
    server_name _;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html; # Vite/React Router 새로고침 404 에러 방지
    }
}